### ISSUE TITLE
Unhandled Exception: int too large to convert to float

### ISSUE THREAD

**Issue by novabandit** [salberin/Solaredge-influxdb#2]
I saw mention of this in the other logged issue, but wanted to mark down another instance of it happening:

```
ekranz@influxdb:~/Solaredge-influxdb$ python3 ./solaredge.py 192.168.1.55 --influxdb 192.168.1.51 --port 1502 -d
/home/ekranz/.local/lib/python3.6/site-packages/aioinflux/compat.py:12: UserWarning: Pandas/Numpy is not available. Support for 'dataframe' mode is disabled.
  warnings.warn(no_pandas_warning)
Starting up solaredge monitoring
Connecting to Solaredge inverter 192.168.1.55 on port 1502 using unitid 1
Writing data to influxDb 192.168.1.51 on port 8086 every     5 seconds
DEBUG:solaredge:Running eventloop
INFO:solaredge:Database opened and initialized
ERROR:solaredge:Unhandled exception: int too large to convert to float
ERROR:solaredge:Unhandled exception: int too large to convert to float
ERROR:solaredge:Unhandled exception: int too large to convert to float
ERROR:solaredge:Unhandled exception: int too large to convert to float
ERROR:solaredge:Unhandled exception: int too large to convert to float
ERROR:solaredge:Unhandled exception: int too large to convert to float
ERROR:solaredge:Unhandled exception: int too large to convert to float
ERROR:solaredge:Unhandled exception: int too large to convert to float
ERROR:solaredge:Unhandled exception: int too large to convert to float
^CTraceback (most recent call last):
  File "./solaredge.py", line 127, in <module>
    asyncio.get_event_loop().run_until_complete(write_to_influx(args.influxdb, args.influxport, args.period))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1415, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
```
This is connecting to a SolarEdge SE11400H-US. I'd be happy to help in any way I can!

Thanks!

**Comment by psy0rz** [comment]
This is some kind of bug or change in the firmware.

A workaround is to add scalefactor=1 before these lines:
```
scalefactor=1
datapoint['fields']['AC Lifetimeproduction'] = trunc_float(data.decode_32bit_uint() * scalefactor)
...
scalefactor=1
datapoint['fields']['DC Voltage'] = trunc_float(data.decode_16bit_uint() * scalefactor)
...
scalefactor=1
datapoint['fields']['DC Current'] = trunc_float(data.decode_16bit_uint() *scalefactor)

```

Somehow the scalefactor is extremely large. Its a number that fill the entire screen :P

Now you will have to figureout the scaling yourself and do it in grafana for example. 

(AC lifetimeproduction is in WH instead of KWH for example)

**Comment by peplin** [comment]
Give #8 a try - that fixed this issue for my SE5000-H-US.
